name: "Welcome Message"
on: [push]
jobs:
  Job-Message-Action-Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Welcome Saad"
      - run: echo "Current OS is ${{runner.os}} "
      - run: echo "Github Event Name is ${{github.event_name}} "
      - run: pwd
      - run: ls ~
      - run: ls ${{github.workspace}}
  Job-Message-Action-Windows:
    runs-on: windows-latest
    steps:
      - name: Get List of Firewall Inbound Rules
        shell: pwsh
        run: |
          Get-NetFirewallRules -Direction Inbound
